FROM node:latest as builder
EXPOSE 80
WORKDIR /usr/local/app
COPY . /usr/local/app
RUN npm install
RUN npm run build --prod
FROM nginx:latest

COPY --from=builder /usr/local/app/dist/angular-votos /usr/share/nginx/html